### ISSUE TITLE
Incorrect usage of whisper

### ISSUE THREAD

**Issue by TeeSlayer** [sirius1242/teeworlds-solofng#1]
See https://github.com/teeworlds/teeworlds/pull/2002

Don't use -1 for the target id when whispering. Happens when trying to suicide while being frozen.

**Comment by sirius1242** [comment]
Thanks for your issue, I will check code of this problem later.

**Comment by sirius1242** [comment]
Sorry, I don't know if [this commit](https://github.com/sirius1242/teeworlds-solofng/commit/7d8449b8b2683366e5a40749c30f38bdbc4e1aed) repair the problem you mean, I check if client id is valid before send whisper.

**Comment by TeeSlayer** [comment]
@sirius1242 No, I just tested it again and it always happens.

This is what I did:

1) Connect with two Teeworlds clients
2) Make client id 1 freeze by standing still.
3) Press kill key for client id 1
4) Client 0 disconnects by timeout (client crashed)
5) Client 1 for some reason gets kicked for forcefully leaving (even though he stayed in the game)

**Comment by TeeSlayer** [comment]
Oh, it's not just -1 that makes Teeworlds crash since the crash also happens with the current master branch for Teeworlds. Invalid IDs in general it seems. So https://github.com/teeworlds/teeworlds/pull/2002 is not solved. :)

**Comment by sirius1242** [comment]
Oh, I recurrent the problem, and the reason why the client crash is segmentation fault.

**Comment by sirius1242** [comment]
I compiled the client which have code after [this commit](https://github.com/teeworlds/teeworlds/pull/2069/commits/63f4b3ec3fa5c73ee3de2553e6899607806ae4b4), and the problem don't appear again, the problem seems caused by client, not server, I think you may need to update the client to solve this problem. And I don't know how to solve it in server, I have tried many other ways, they all will make others see this message or cause segment fault.

**Comment by sirius1242** [comment]
Oh, I just make the whisper come from self, I think this problem is solved.

**Comment by sirius1242** [comment]
I changed it to broadcast now, I think this will be better.
