### ISSUE TITLE
Mysterious and invisible death tile

### ISSUE THREAD

**Issue by TeeSlayer** [sirius1242/teeworlds-solofng#3]
https://lolinet.info/download/openfng.demo

What is happening here? It's always at this spot when I restart the server, but after voting for another map, it's suddenly gone.

**Comment by sirius1242** [comment]
Sorry, I try to reproduce the bug, but I don't find this problem. This tile is for display team score in origin plan, but I can't find proper map item index for it, it may cause death before, but now it won't. I think maybe your server or map is in old version, you can update your map and server, I think the problem will be solved.

**Comment by TeeSlayer** [comment]
That's the commit I'm using: https://github.com/sirius1242/teeworlds-solofng/commit/a137618e8bfe923cc23f4e9fc832a4338aed963d (Server is L#12 and on 0.7.3)

I got all the maps from [CHN][USTC-LUG] yesterday (I think that's your server).

Maybe my explanation was a bit vague:

I can only reproduce this bug after a full restart. Not "restart" or "reload" in the rcon (those two commands don't do anything), but actually killing the Teeworlds server process and then starting it again. Apparently calling 'sv_map' fixes this permanently.

**Comment by sirius1242** [comment]
Oh, maybe my explanation was a bit vague, too. that server use openfng5-Beat_3, because after add openfng, map must change, there are difference between red shrine and blue shrine. You may still use the old map (this demo use openfng5-Beat_2), try to use openfng5-Beat_3 may solve the problem. And I don't know if you noticed that all the shrines are red shrine.
